version: '3.8'

services:
  adabasdb:
    image: softwareag/adabas-ce:latest
    container_name: adabas-db
    ports:
      - "60001:60001"
    environment:
      - ADABAS_DB_ID=1
      - ADABAS_LOGGING=debug
    volumes:
      - ./data/adabas-db/var/adabas/data
      - ./logs/adabas-db:/var/adabas/log

  adabas_manager:
    image: softwareag/adabasmanager-ce:latest
    container_name: adabas-manager
    depends_on:
      - adabas-db
    ports:
      - "60002:60002"
    environment:
      - ADABAS_DB_HOST=adabasdb
      - ADABAS_DB_PORT=60001
      - ADABAS_MANAGER_LOGGING=debug
    volumes:
      - ./data/adabas_manager:/var/adabas/manager/data
      - ./logs/adabas_manager:/var/adabas/manager/log

  natural_ce:
    image: softwareag/natural-ce:latest
    container_name: natural-ce
    depends_on:
      - adabas-db
      - adabas-manager
    ports:
      - "9000:9000"
    environment:
      - NATURAL_DB_ID=1
      - ADABAS_DB_HOST=adabasdb
      - ADABAS_DB_PORT=60001
      - NATURAL_LOGGING=debug
    volumes:
      - ./data/natural_ce:/var/natural_ce/data
      - ./logs/natural_ce:/var/natural_ce/log

volumes:
  adabas_data:
    external: false
  adabas_log:
    external: false
  adabas_manager_data:
    external: false
  adabas_manager_log:
    external: false
  natural_ce_data:
    external: false
  natural_ce_log:
    external: false
